import { Container } from '@/components/Container';
import { Nav } from '@/components/Nav';
import SearchForm from '@/components/SearchForm';
import { VerticalContainer } from '@/components/VerticalContainer';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' data-theme='dark'>
      <body>
        <VerticalContainer>
          <header>
            <Container>
              <SearchForm />
            </Container>
            <Container>
              <Nav />
            </Container>
          </header>
          <main>
            <Container>{children}</Container>
          </main>
          <footer></footer>
        </VerticalContainer>
      </body>
    </html>
  );
}
