import { Container } from '@/components/Container';
import { useLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { ToastContainer } from 'react-toastify';
import { Nav } from '@/components/Nav';
import { Stack } from '@/components/Stack';
import '../globals.css';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const locale = useLocale();

  if (params.locale !== locale) {
    notFound();
  }

  return (
    <html lang={locale} data-theme='dark'>
      <body>
        <Stack>
          <header>
            <Container>
              <Nav />
            </Container>
          </header>
          <main>
            <Container>{children}</Container>
          </main>
          <footer></footer>
        </Stack>
        <ToastContainer
          position='top-right'
          autoClose={5000}
          hideProgressBar
          newestOnTop
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable={false}
          pauseOnHover
          theme='dark'
        />
      </body>
    </html>
  );
}
