import { Container } from '@/components/Container';
import { Nav } from '@/components/Nav';
import { SearchForm } from '@/components/SearchForm';
import { Stack } from '@/components/Stack';
import '../globals.css';
import { notFound } from 'next/navigation';
import { useLocale } from 'next-intl';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const locale = useLocale();

  if (params.locale !== locale) {
    notFound();
  }

  return (
    <html lang={locale} data-theme='dark'>
      <body>
        <Stack>
          <header>
            <Container>
              <Nav />
            </Container>
          </header>
          <main>
            <Container>{children}</Container>
          </main>
          <footer></footer>
        </Stack>
      </body>
    </html>
  );
}
